# SPDX-FileCopyrightText: 2025 igniter_css contributors <https://github.com/ash-project/igniter_css/graphs/contributors>
#
# SPDX-License-Identifier: MIT

name: CI
on:
  push:
    tags:
      - "v*"
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:
jobs:
  ash-ci:
    uses: ash-project/ash/.github/workflows/ash-ci.yml@main
    permissions:
      contents: write
      pages: write
      id-token: write
      security-events: write
    with:
      spark-formatter: false
      spark-cheat-sheets: false
      sobelow: false
      igniter-upgrade: false
      rustler-precompiled-module: IgniterCss.Native
      rust-crate-dir: native/igniter_css
      reuse: true
    secrets:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
